ingress:
  # allows you to specify custom hosts
  customHosts:
    # specify your ngrok custom domain here
    # such as
    hook: "1fb1-198-54-129-52.ngrok.io"
    # so that webhooks from, say, github.com, will work to your local laptop
    hook: ""


kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"
